### PR TITLE
remove deprecated file operations

### PR DESCRIPTION
**Pull request by zhangjin-007**

### CODE REVIEW

**Comment by hufeng** [comment]
Great job, LGTM

But I want to know why my vscode not tell me deprecated info. 😂

**Comment by hufeng** [comment]
Lint have a problem, in workflow, when scan error files, github action must failed, but it pass now

Screen Shot 2022-10-24 at 22 24 26

May be err files not empty, exit(1)

**Comment by hufeng** [comment]
@zhangjin-007 please resolve branch conflicts

**Comment by zhangjin-007** [comment]
I have resolved the conflict

**Comment by hufeng** [comment]
This pr contains many file changes，I suggest pulling the latest code and giving the pr

**Pull request closed without merging**
