### PR TITLE
add one FAQ ; add enum transfer example 

### PR DESCRIPTION
**Pull request by creasy2010**
1. add one FAQ ;
2. add enum transfer example;

### CODE REVIEW

**Comment by ralf0131** [comment]
@hufeng Could you help to review it?

**Comment by hufeng** [comment]
yes,  We are discussing technical details.

Huxing Zhang <notifications@github.com> 于2019年5月24日周五 下午3:56写道：

**Comment by hufeng** [comment]
@ralf0131 ok

**Comment by hufeng** [comment]
@ralf0131 please help us merge this

**Pull request merged**
