### PR TITLE
rename dubbo-js node_module name and change version 3.0.0

### PR DESCRIPTION
**Pull request by hufeng**

### CODE REVIEW

**Comment by ralf0131** [comment]
Does changing this version number mean a new release? If so, I suggest to go to dev@ list to discuss and vote for it.

**Comment by hufeng** [comment]
@ralf0131 yes, I agree

**Comment by hufeng** [comment]
@ralf0131  Can we merge this pull request?

**Comment by ralf0131** [comment]
I just what to confirm, change the version does not mean a release, right? If so, we can merge it.

**Comment by hufeng** [comment]
@ralf0131 yes, does not mean a release, Only in the future we will release a new version based on this version.

**Comment by hufeng** [comment]
yes, does not mean a release, Only in the future we will release a new
version based on this version.

Huxing Zhang <notifications@github.com> 于2019年7月5日周五 上午6:51写道：

**Pull request merged**
